<?php
/**
 * ZoneTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ZoneTest Class Doc Comment
 *
 * @category    Class
 * @description This represents an authoritative DNS Zone.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ZoneTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Zone"
     */
    public function testZone()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "kind"
     */
    public function testPropertyKind()
    {
    }

    /**
     * Test attribute "rrsets"
     */
    public function testPropertyRrsets()
    {
    }

    /**
     * Test attribute "serial"
     */
    public function testPropertySerial()
    {
    }

    /**
     * Test attribute "notified_serial"
     */
    public function testPropertyNotifiedSerial()
    {
    }

    /**
     * Test attribute "edited_serial"
     */
    public function testPropertyEditedSerial()
    {
    }

    /**
     * Test attribute "masters"
     */
    public function testPropertyMasters()
    {
    }

    /**
     * Test attribute "dnssec"
     */
    public function testPropertyDnssec()
    {
    }

    /**
     * Test attribute "nsec3param"
     */
    public function testPropertyNsec3param()
    {
    }

    /**
     * Test attribute "nsec3narrow"
     */
    public function testPropertyNsec3narrow()
    {
    }

    /**
     * Test attribute "presigned"
     */
    public function testPropertyPresigned()
    {
    }

    /**
     * Test attribute "soa_edit"
     */
    public function testPropertySoaEdit()
    {
    }

    /**
     * Test attribute "soa_edit_api"
     */
    public function testPropertySoaEditApi()
    {
    }

    /**
     * Test attribute "api_rectify"
     */
    public function testPropertyApiRectify()
    {
    }

    /**
     * Test attribute "zone"
     */
    public function testPropertyZone()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "nameservers"
     */
    public function testPropertyNameservers()
    {
    }

    /**
     * Test attribute "master_tsig_key_ids"
     */
    public function testPropertyMasterTsigKeyIds()
    {
    }

    /**
     * Test attribute "slave_tsig_key_ids"
     */
    public function testPropertySlaveTsigKeyIds()
    {
    }
}
