<?php
/**
 * TsigkeyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TsigkeyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TsigkeyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createTSIGKey
     *
     * Add a TSIG key.
     *
     */
    public function testCreateTSIGKey()
    {
    }

    /**
     * Test case for deleteTSIGKey
     *
     * Delete the TSIGKey with tsigkey_id.
     *
     */
    public function testDeleteTSIGKey()
    {
    }

    /**
     * Test case for getTSIGKey
     *
     * Get a specific TSIGKeys on the server, including the actual key.
     *
     */
    public function testGetTSIGKey()
    {
    }

    /**
     * Test case for listTSIGKeys
     *
     * Get all TSIGKeys on the server, except the actual key.
     *
     */
    public function testListTSIGKeys()
    {
    }

    /**
     * Test case for putTSIGKey
     *
     * .
     *
     */
    public function testPutTSIGKey()
    {
    }
}
