<?php
/**
 * ZonecryptokeyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ZonecryptokeyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZonecryptokeyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCryptokey
     *
     * Creates a Cryptokey.
     *
     */
    public function testCreateCryptokey()
    {
    }

    /**
     * Test case for deleteCryptokey
     *
     * This method deletes a key specified by cryptokey_id..
     *
     */
    public function testDeleteCryptokey()
    {
    }

    /**
     * Test case for getCryptokey
     *
     * Returns all data about the CryptoKey, including the privatekey..
     *
     */
    public function testGetCryptokey()
    {
    }

    /**
     * Test case for listCryptokeys
     *
     * Get all CryptoKeys for a zone, except the privatekey.
     *
     */
    public function testListCryptokeys()
    {
    }

    /**
     * Test case for modifyCryptokey
     *
     * This method (de)activates a key from zone_name specified by cryptokey_id.
     *
     */
    public function testModifyCryptokey()
    {
    }
}
