<?php
/**
 * ZonemetadataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ZonemetadataApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZonemetadataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMetadata
     *
     * Creates a set of metadata entries.
     *
     */
    public function testCreateMetadata()
    {
    }

    /**
     * Test case for deleteMetadata
     *
     * Delete all items of a single kind of domain metadata..
     *
     */
    public function testDeleteMetadata()
    {
    }

    /**
     * Test case for getMetadata
     *
     * Get the content of a single kind of domain metadata as a Metadata object..
     *
     */
    public function testGetMetadata()
    {
    }

    /**
     * Test case for listMetadata
     *
     * Get all the Metadata associated with the zone..
     *
     */
    public function testListMetadata()
    {
    }

    /**
     * Test case for modifyMetadata
     *
     * Replace the content of a single kind of domain metadata..
     *
     */
    public function testModifyMetadata()
    {
    }
}
