<?php
/**
 * ZonesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ZonesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZonesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for axfrExportZone
     *
     * Returns the zone in AXFR format..
     *
     */
    public function testAxfrExportZone()
    {
    }

    /**
     * Test case for axfrRetrieveZone
     *
     * Retrieve slave zone from its master..
     *
     */
    public function testAxfrRetrieveZone()
    {
    }

    /**
     * Test case for createZone
     *
     * Creates a new domain, returns the Zone on creation..
     *
     */
    public function testCreateZone()
    {
    }

    /**
     * Test case for deleteZone
     *
     * Deletes this zone, all attached metadata and rrsets..
     *
     */
    public function testDeleteZone()
    {
    }

    /**
     * Test case for listZone
     *
     * zone managed by a server.
     *
     */
    public function testListZone()
    {
    }

    /**
     * Test case for listZones
     *
     * List all Zones in a server.
     *
     */
    public function testListZones()
    {
    }

    /**
     * Test case for notifyZone
     *
     * Send a DNS NOTIFY to all slaves..
     *
     */
    public function testNotifyZone()
    {
    }

    /**
     * Test case for patchZone
     *
     * Creates/modifies/deletes RRsets present in the payload and their comments. Returns 204 No Content on success..
     *
     */
    public function testPatchZone()
    {
    }

    /**
     * Test case for putZone
     *
     * Modifies basic zone data..
     *
     */
    public function testPutZone()
    {
    }

    /**
     * Test case for rectifyZone
     *
     * Rectify the zone data..
     *
     */
    public function testRectifyZone()
    {
    }
}
